version: '3.8'

services:
    mysql:
        image: 'mysql'
        restart: always
        container_name: 'typeorm-mysql'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'admin'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'test'
            MYSQL_DATABASE: 'mydb'
        volumes:
            - mysql_data:/var/lib/mysql

    mongodb:
        image: 'mongo'
        restart: always
        container_name: 'nestjs-mongo'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongo_data:/data/db

volumes:
    mysql_data:
    mongo_data:
